import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex items-center justify-center gap-5 pt-3">
        <Link href="/client-todo" className="px-4 py-2 text-white bg-blue-500 rounded-lg">
      1. Client Todos
    </Link>
    <Link href="/server-file-todo" className="px-4 py-2 text-white bg-blue-500 rounded-lg">
      2. Server File Todos
    </Link>
    <Link href="/client-file-todo" className="px-4 py-2 text-white bg-blue-500 rounded-lg">
      3. Client File Todos
    </Link>
    </div>
      
        {children}
      </body>
    </html>    
  );
}
